steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']

- name: 'node'
  entrypoint: 'npm'
  args: ["run", "create-env"]
  env:
    - 'MONGODBURL=${_MONGODBURL}'
    - 'MONGODBURLTEST=${_MONGODBURL}'
    - 'JWTSECRET=${_JWTSECRET}'

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'test']

# europe-docker.pkg.dev/sdeservices/eu.gcr.io
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-docker.pkg.dev/$PROJECT_ID/sdeservices/latest', '.' ]
images:
- 'europe-docker.pkg.dev/$PROJECT_ID/sdeservices/latest'

