steps:
- name: 'node'
  description: 'install dependencies'
  entrypoint: 'npm'
  args: ['install', '--only-production']

- name: 'node'
  description: 'create the .env file'
  entrypoint: 'npm'
  # this command must be created on the package.json file
  args: ["run", "create-env"]
  # you need to enter the env variables for the server in the cloud build > trigger page > advanced > substitution variables
  env:
    - 'MONGODBURL=${_MONGODBURL}'
    - 'MONGODBURLTEST=${_MONGODBURLTEST}'
    - 'JWTSECRET=${_JWTSECRET}'

- name: 'node'
  description: 'test the app'
  entrypoint: 'npm'
  args: ['run', 'test']

- name: 'gcr.io/cloud-builders/docker'
  description: 'create the docker image from the Dockerfile'
  # third parameter is ${SERVER_LOCATION}-docker.pkg.dev/${PROJECT_NAME}/${ARTIFACT_REPOSITORY_NAME}/${DOCKER_IMAGE_NAME}
  # you can find it in the Artifact Registry page
  # ${DOCKER_IMAGE_NAME} can be a new one
  args: [ 'build', '-t', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service', '.' ]

- name: 'gcr.io/cloud-builders/docker'
  description: 'save docker image to Artifact Registry'
  # same docker image name as before
  args: ['push', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  # the fifth parameter is the same docker image name as before
  # the third one is the name of the service in the Cloud Run page (it can be a new name)
  args: ['run', 'deploy', 'data-service', '--image', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service', '--region', 'europe-west8', '--platform', 'managed']

images: ['europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service']
