steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']

- name: 'node'
  entrypoint: 'npm'
  args: ["run", "create-env"]
  env:
    - 'MONGODBURL=${_MONGODBURL}'
    - 'MONGODBURLTEST=${_MONGODBURL}'
    - 'JWTSECRET=${_JWTSECRET}'

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'test']
