steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']

- name: 'node'
  entrypoint: 'npm'
  args: ["run", "create-env"]
  env:
    - 'MONGODBURL=${_MONGODBURL}'
    - 'MONGODBURLTEST=${_MONGODBURLTEST}'
    - 'JWTSECRET=${_JWTSECRET}'

- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'test']

# save docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service', '.' ]
#images: ['europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'sdeservices', '--image', 'europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service', '--region', 'europe-west8', '--platform', 'managed']

images: ['europe-west8-docker.pkg.dev/sdeservices/sde-services-docker/data-service']
